# Generated by Django 3.2.12 on 2022-04-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Geschlecht',
                'verbose_name_plural': 'Geschlechter',
                'db_table': 'gender',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profile',
                'db_table': 'profile',
                'managed': True,
            },
        ),
    ]
